# Regression Model with Keras

## Introduction
Keras is a high-level API for building deep learning models. It has gained favor for its ease of use and syntactic simplicity facilitating fast development. As you will see in this lab and the other labs in this course, building a very complex deep learning network can be achieved with Keras with only few lines of code. You will appreciate Keras even more, once you learn how to build deep models using PyTorch and TensorFlow in the other courses.

## Download and Clean Dataset
Let's start by importing the pandas and numpy Libraries

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter('ignore', FutureWarning)

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

<strong>1. Cement</strong>

<strong>2. Blast Furnace Slag</strong>

<strong>3. Fly Ash</strong>

<strong>4. Water</strong>

<strong>5. Superplasticizer</strong>

<strong>6. Coarse Aggregate</strong>

<strong>7. Fine Aggregate</strong>

In [2]:
concrete_data = pd.read_csv('concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa.

In [3]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

#### Split data into predictors and target
The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [4]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

Let's do a quick sanity check of the predictors and the target dataframe

In [5]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [6]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [7]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Let's save the number of predictors to *n_cols* since we will need this number when building our network.

In [8]:
n_cols = predictors_norm.shape[1] # number of predictors

## Import Keras
Recall from the videos that Keras normally runs on top of a low-level library such as TensorFlow. This means that to be able to use the Keras library, you will have to install TensorFlow first and when you import the Keras library, it will be explicitly displayed what backend was used to install the Keras library. In CC Labs, we used TensorFlow as the backend to install Keras, so it should clearly print that when we import Keras.

#### Let's go ahead and import the Keras library

In [9]:
import keras

Let's import the rest of the packages from the Keras library that we will need to build our regressoin model.

In [10]:
from keras.models import Sequential
from keras.layers import Dense

## Build a Neural Network
Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [11]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(50, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

## Train and Test the Network
Let's call the function now to create our model.

In [12]:
# build the model
model = regression_model()

C:\Users\Lakshya Saxena\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [14]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 88ms/step - loss: 1663.1151 - val_loss: 1158.2476
Epoch 2/100
23/23 - 0s - 20ms/step - loss: 1538.4327 - val_loss: 1039.3546
Epoch 3/100
23/23 - 0s - 7ms/step - loss: 1333.6693 - val_loss: 850.7542
Epoch 4/100
23/23 - 0s - 6ms/step - loss: 1026.5178 - val_loss: 607.6802
Epoch 5/100
23/23 - 0s - 7ms/step - loss: 657.6771 - val_loss: 377.6605
Epoch 6/100
23/23 - 0s - 8ms/step - loss: 368.4958 - val_loss: 239.8639
Epoch 7/100
23/23 - 0s - 7ms/step - loss: 247.0867 - val_loss: 195.0508
Epoch 8/100
23/23 - 0s - 7ms/step - loss: 220.9394 - val_loss: 183.5495
Epoch 9/100
23/23 - 0s - 6ms/step - loss: 207.5652 - val_loss: 176.8099
Epoch 10/100
23/23 - 0s - 6ms/step - loss: 197.8211 - val_loss: 170.0153
Epoch 11/100
23/23 - 0s - 9ms/step - loss: 190.5752 - val_loss: 167.5996
Epoch 12/100
23/23 - 0s - 7ms/step - loss: 184.1445 - val_loss: 163.0532
Epoch 13/100
23/23 - 0s - 7ms/step - loss: 179.5436 - val_loss: 163.2102
Epoch 14/100
23/23 - 0s - 6ms/step - loss: 174.3463 - val_loss: 160.2960
Epoch 15/100
23/23 - 0s - 6ms/step - loss: 170.5110 - val_loss: 159.0893
Epoch 16/100
23/23 - 0s - 7ms/step - loss: 167.3842 - val_loss: 157.9240
Epoch 17/100
23/23 - 0s - 6ms/step - loss: 163.5976 - val_loss: 154.5818
Epoch 18/100
23/23 - 0s - 6ms/step - loss: 160.8679 - val_loss: 153.2966
Epoch 19/100
23/23 - 0s - 5ms/step - loss: 158.4528 - val_loss: 152.5261
Epoch 20/100
23/23 - 0s - 6ms/step - loss: 155.5128 - val_loss: 152.1234
Epoch 21/100
23/23 - 0s - 6ms/step - loss: 153.4366 - val_loss: 152.1920
Epoch 22/100
23/23 - 0s - 8ms/step - loss: 150.9144 - val_loss: 150.7406
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 148.9697 - val_loss: 150.4892
Epoch 24/100
23/23 - 0s - 6ms/step - loss: 147.3195 - val_loss: 148.4631
Epoch 25/100
23/23 - 0s - 6ms/step - loss: 145.2724 - val_loss: 151.0904
Epoch 26/100
23/23 - 0s - 6ms/step - loss: 143.4696 - val_loss: 147.8836
Epoch 27/100
23/23 - 0s - 6ms/step - loss: 142.6285 - val_loss: 146.5155
Epoch 28/100
23/23 - 0s - 6ms/step - loss: 139.8873 - val_loss: 149.8754
Epoch 29/100
23/23 - 0s - 7ms/step - loss: 137.8634 - val_loss: 148.8363
Epoch 30/100
23/23 - 0s - 6ms/step - loss: 136.3551 - val_loss: 148.7122
Epoch 31/100
23/23 - 0s - 7ms/step - loss: 134.5600 - val_loss: 146.0639
Epoch 32/100
23/23 - 0s - 15ms/step - loss: 133.2983 - val_loss: 148.2139
Epoch 33/100
23/23 - 0s - 6ms/step - loss: 131.8340 - val_loss: 148.6021
Epoch 34/100
23/23 - 0s - 6ms/step - loss: 129.6746 - val_loss: 147.5505
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 128.3264 - val_loss: 147.2940
Epoch 36/100
23/23 - 0s - 8ms/step - loss: 126.9973 - val_loss: 145.8137
Epoch 37/100
23/23 - 0s - 7ms/step - loss: 125.3807 - val_loss: 148.3843
Epoch 38/100
23/23 - 0s - 6ms/step - loss: 123.6620 - val_loss: 145.7253
Epoch 39/100
23/23 - 0s - 6ms/step - loss: 122.3894 - val_loss: 144.4019
Epoch 40/100
23/23 - 0s - 6ms/step - loss: 121.5851 - val_loss: 144.5488
Epoch 41/100
23/23 - 0s - 6ms/step - loss: 119.2281 - val_loss: 143.2164
Epoch 42/100
23/23 - 0s - 6ms/step - loss: 117.6072 - val_loss: 144.9485
Epoch 43/100
23/23 - 0s - 7ms/step - loss: 116.4608 - val_loss: 143.9314
Epoch 44/100
23/23 - 0s - 6ms/step - loss: 114.3305 - val_loss: 142.2265
Epoch 45/100
23/23 - 0s - 6ms/step - loss: 114.1687 - val_loss: 142.0318
Epoch 46/100
23/23 - 0s - 8ms/step - loss: 110.8238 - val_loss: 141.0292
Epoch 47/100
23/23 - 0s - 6ms/step - loss: 109.8973 - val_loss: 140.8087
Epoch 48/100
23/23 - 0s - 6ms/step - loss: 108.4664 - val_loss: 138.5992
Epoch 49/100
23/23 - 0s - 5ms/step - loss: 106.4853 - val_loss: 140.2699
Epoch 50/100
23/23 - 0s - 6ms/step - loss: 104.8296 - val_loss: 140.1262
Epoch 51/100
23/23 - 0s - 7ms/step - loss: 102.9875 - val_loss: 136.4417
Epoch 52/100
23/23 - 0s - 6ms/step - loss: 100.9426 - val_loss: 136.2447
Epoch 53/100
23/23 - 0s - 6ms/step - loss: 98.7935 - val_loss: 136.0043
Epoch 54/100
23/23 - 0s - 6ms/step - loss: 96.4339 - val_loss: 137.0949
Epoch 55/100
23/23 - 0s - 13ms/step - loss: 94.5204 - val_loss: 135.3197
Epoch 56/100
23/23 - 0s - 5ms/step - loss: 91.5413 - val_loss: 132.8963
Epoch 57/100
23/23 - 0s - 8ms/step - loss: 88.6147 - val_loss: 129.7828
Epoch 58/100
23/23 - 0s - 7ms/step - loss: 85.6445 - val_loss: 132.4443
Epoch 59/100
23/23 - 0s - 6ms/step - loss: 83.5839 - val_loss: 128.7239
Epoch 60/100
23/23 - 0s - 6ms/step - loss: 80.8975 - val_loss: 125.6622
Epoch 61/100
23/23 - 0s - 6ms/step - loss: 78.1768 - val_loss: 124.7592
Epoch 62/100
23/23 - 0s - 6ms/step - loss: 75.8351 - val_loss: 125.3883
Epoch 63/100
23/23 - 0s - 7ms/step - loss: 73.3614 - val_loss: 120.2227
Epoch 64/100
23/23 - 0s - 6ms/step - loss: 71.0792 - val_loss: 118.4351
Epoch 65/100
23/23 - 0s - 6ms/step - loss: 68.4991 - val_loss: 114.9777
Epoch 66/100
23/23 - 0s - 6ms/step - loss: 66.7187 - val_loss: 115.7734
Epoch 67/100
23/23 - 0s - 8ms/step - loss: 64.6847 - val_loss: 108.8590
Epoch 68/100
23/23 - 0s - 6ms/step - loss: 62.9119 - val_loss: 111.7928
Epoch 69/100
23/23 - 0s - 7ms/step - loss: 60.6307 - val_loss: 112.5416
Epoch 70/100
23/23 - 0s - 8ms/step - loss: 59.4515 - val_loss: 111.5192
Epoch 71/100
23/23 - 0s - 6ms/step - loss: 58.4052 - val_loss: 104.4326
Epoch 72/100
23/23 - 0s - 8ms/step - loss: 57.4018 - val_loss: 112.3913
Epoch 73/100
23/23 - 0s - 6ms/step - loss: 55.3598 - val_loss: 114.4146
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 53.8026 - val_loss: 102.5101
Epoch 75/100
23/23 - 0s - 6ms/step - loss: 53.2417 - val_loss: 108.4991
Epoch 76/100
23/23 - 0s - 5ms/step - loss: 51.1020 - val_loss: 111.4450
Epoch 77/100
23/23 - 0s - 8ms/step - loss: 50.0392 - val_loss: 107.2865
Epoch 78/100
23/23 - 0s - 6ms/step - loss: 49.5758 - val_loss: 110.2436
Epoch 79/100
23/23 - 0s - 8ms/step - loss: 48.0674 - val_loss: 110.7974
Epoch 80/100
23/23 - 0s - 6ms/step - loss: 46.6634 - val_loss: 105.3609
Epoch 81/100
23/23 - 0s - 6ms/step - loss: 46.0567 - val_loss: 113.4711
Epoch 82/100
23/23 - 0s - 6ms/step - loss: 44.8842 - val_loss: 107.7790
Epoch 83/100
23/23 - 0s - 5ms/step - loss: 43.9749 - val_loss: 110.0795
Epoch 84/100
23/23 - 0s - 6ms/step - loss: 43.2952 - val_loss: 118.4852
Epoch 85/100
23/23 - 0s - 7ms/step - loss: 42.7632 - val_loss: 112.9166
Epoch 86/100
23/23 - 0s - 6ms/step - loss: 41.3347 - val_loss: 109.6744
Epoch 87/100
23/23 - 0s - 6ms/step - loss: 41.6653 - val_loss: 115.2397
Epoch 88/100
23/23 - 0s - 6ms/step - loss: 40.7215 - val_loss: 115.9459
Epoch 89/100
23/23 - 0s - 6ms/step - loss: 40.0690 - val_loss: 114.6552
Epoch 90/100
23/23 - 0s - 8ms/step - loss: 39.7291 - val_loss: 114.7820
Epoch 91/100
23/23 - 0s - 6ms/step - loss: 38.8917 - val_loss: 110.5492
Epoch 92/100
23/23 - 0s - 5ms/step - loss: 38.6529 - val_loss: 111.5039
Epoch 93/100
23/23 - 0s - 5ms/step - loss: 37.5935 - val_loss: 120.5933
Epoch 94/100
23/23 - 0s - 7ms/step - loss: 36.8571 - val_loss: 112.4997
Epoch 95/100
23/23 - 0s - 6ms/step - loss: 36.5812 - val_loss: 120.1470
Epoch 96/100
23/23 - 0s - 6ms/step - loss: 35.8254 - val_loss: 112.6090
Epoch 97/100
23/23 - 0s - 5ms/step - loss: 35.6292 - val_loss: 116.0507
Epoch 98/100
23/23 - 0s - 7ms/step - loss: 35.4348 - val_loss: 124.7284
Epoch 99/100
23/23 - 0s - 7ms/step - loss: 34.7638 - val_loss: 126.6988
Epoch 100/100
23/23 - 0s - 5ms/step - loss: 34.3119 - val_loss: 112.5402

<strong>You can refer to this [link](https://keras.io/models/sequential/) to learn about other functions that you can use for prediction or evaluation.</strong>