## Reading data from dataset

In [1]:
# For avoiding future warnings while training model
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
# Reading data from CSV
data = pd.read_csv('concrete_data.csv')
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
# Specifying columns for the predictors and target values
data_columns = data.columns
predictors = data[data_columns[data_columns != 'Strength']]
target = data['Strength']

In [4]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [5]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

## Splitting the data

In [6]:
# Using Train Test Split from SKLEARN LIBRARY
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    predictors, target, test_size=0.3, random_state=42)

# Training data = 70% and Testing Data = 30%

## Building a Neural Network

In [7]:
# Importing the Keras Library for creating model
import keras
from keras.models import Sequential
from keras.layers import Dense

## Train and Test the Network

Here, we are creating a model which has 1 Hidden Layer of 10 nodes and Activation Function is ReLU. Optimizer is adam and Loss Function is mean_squared_error. We are storing the loss values in a list as well... there are 50 epochs

In [8]:
# create model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(predictors.shape[1],)))
model.add(Dense(1))

# compiling model with MSE as the Loss Function
model.compile(optimizer='adam', loss='mse')

# Train the model and store the history
history = model.fit(X_train, y_train, epochs=50)

# Storing the MSE values in the list
mse_list = history.history['loss']

C:\Users\Lakshya Saxena\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2423.0205
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1972.0557
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1471.0260
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 961.1284
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 669.8605
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 502.5926
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 386.4432
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 331.7518
Epoch 9/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 243.1705
Epoch 10/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 230.7460
Epoch 11/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 170.0932
Epoch 12/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 200.1444
Epoch 13/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 172.4047
Epoch 14/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.2382
Epoch 15/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 149.9368
Epoch 16/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 145.9668
Epoch 17/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 152.8268
Epoch 18/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 139.8139
Epoch 19/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 152.2074
Epoch 20/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 143.5155
Epoch 21/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 130.6002
Epoch 22/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 134.9062
Epoch 23/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 136.3657
Epoch 24/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 135.6749
Epoch 25/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 135.7140
Epoch 26/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 119.5176
Epoch 27/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 124.2881
Epoch 28/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 123.0972
Epoch 29/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 118.2725
Epoch 30/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 113.4603
Epoch 31/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 115.4509
Epoch 32/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 110.6746
Epoch 33/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 117.6256
Epoch 34/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 115.6435
Epoch 35/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 118.56419
Epoch 36/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 121.2508
Epoch 37/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 105.8269
Epoch 38/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 122.4972
Epoch 39/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 117.6575
Epoch 40/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 115.2931
Epoch 41/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 117.2630
Epoch 42/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 108.7428
Epoch 43/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 123.0233
Epoch 44/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 114.1318
Epoch 45/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 107.6980
Epoch 46/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 106.0136
Epoch 47/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 115.8092
Epoch 48/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 107.2619
Epoch 49/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 109.2060
Epoch 50/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 112.6846

In [9]:
print(mse_list)

[2406.792236328125, 1804.43603515625, 1273.061767578125, 872.3549194335938, 643.8631591796875, 473.1540832519531, 366.7294921875, 295.9100036621094, 248.11436462402344, 220.08396911621094, 198.15074157714844, 190.80471801757812, 178.22792053222656, 169.1303253173828, 162.6165008544922, 155.9987030029297, 147.9239501953125, 145.16879272460938, 142.55604553222656, 137.1816864013672, 135.0589599609375, 132.0039825439453, 130.54437255859375, 127.49929809570312, 125.05223846435547, 124.18296813964844, 122.58653259277344, 119.83563232421875, 118.7420883178711, 118.4241714477539, 116.34162902832031, 117.47209930419922, 117.28160858154297, 114.4057846069336, 114.31710815429688, 114.78826904296875, 118.83830261230469, 113.71388244628906, 112.4251708984375, 111.28411865234375, 115.29634094238281, 114.31168365478516, 113.6756591796875, 112.19082641601562, 110.01410675048828, 110.72096252441406, 108.93144226074219, 109.4429702758789, 111.95549774169922, 117.27642822265625]

In [10]:
# Mean value of the Losses throughout the Training
print(np.mean(mse_list))

275.2174710083008

In [11]:
# Standard Deviation of the Losses throughout the Training
print(np.std(mse_list))

431.25157309008955