## Reading data from dataset

In [1]:
# For avoiding future warnings while training model
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
# Reading data from CSV
data = pd.read_csv('concrete_data.csv')
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
# Specifying columns for the predictors and target values
data_columns = data.columns
predictors = data[data_columns[data_columns != 'Strength']]
target = data['Strength']

In [4]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [5]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

## Normalizing the data

In [6]:
# Normalize data by subtracting the mean from the individual predictors and dividing by standard deviation
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

## Splitting the data

In [7]:
# Using Train Test Split from SKLEARN LIBRARY
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    predictors_norm, target, test_size=0.3, random_state=42)

# Training data = 70% and Testing Data = 30%

## Building a Neural Network

In [8]:
# Importing the Keras Library for creating model
import keras
from keras.models import Sequential
from keras.layers import Dense

## Train and Test the Network
Here, we are creating a model which has 1 Hidden Layer of 10 nodes and Activation Function is ReLU. Optimizer is adam and Loss Function is mean_squared_error. We are storing the loss values in a list as well... there are 50 epochs

In [9]:
# create model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(predictors_norm.shape[1],)))
model.add(Dense(1))

# compiling model with MSE as the Loss Function
model.compile(optimizer='adam', loss='mse')

# Train the model and store the history
history = model.fit(X_train, y_train, epochs=50)

# Storing the MSE values in the list
mse_list = history.history['loss']

C:\Users\Lakshya Saxena\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1664.7994
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1671.1455
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1623.9430
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1516.8279
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1570.5702
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1526.9114
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1462.0050
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1479.6626
Epoch 9/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1497.7422
Epoch 10/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1395.9779
Epoch 11/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1442.8920
Epoch 12/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1475.6537
Epoch 13/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1422.3444
Epoch 14/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1348.5802
Epoch 15/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1389.0256
Epoch 16/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229.4835
Epoch 17/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1307.8082
Epoch 18/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229.1880
Epoch 19/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1230.4906
Epoch 20/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1201.4812
Epoch 21/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1216.8475
Epoch 22/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1126.0531
Epoch 23/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1191.8868
Epoch 24/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1060.1340
Epoch 25/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1071.2439
Epoch 26/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 975.4875
Epoch 27/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1032.9448
Epoch 28/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 934.0031
Epoch 29/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 968.9673
Epoch 30/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 964.3528
Epoch 31/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 932.6428
Epoch 32/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 892.5571
Epoch 33/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 828.8190
Epoch 34/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 792.6827
Epoch 35/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 759.3254
Epoch 36/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 827.7838
Epoch 37/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 736.0695
Epoch 38/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 712.0899
Epoch 39/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 730.7631
Epoch 40/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 642.4714
Epoch 41/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 622.0701
Epoch 42/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 670.5328
Epoch 43/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 614.1301
Epoch 44/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 570.2696
Epoch 45/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 539.5564
Epoch 46/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 558.6549
Epoch 47/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 511.7820
Epoch 48/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 511.9554
Epoch 49/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - loss: 450.7024
Epoch 50/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 446.5589

In [10]:
print(mse_list)

[1612.391845703125, 1594.1021728515625, 1575.975341796875, 1557.7735595703125, 1539.2896728515625, 1520.447509765625, 1500.794921875, 1481.2354736328125, 1460.8115234375, 1439.88525390625, 1418.423583984375, 1396.0902099609375, 1373.5994873046875, 1349.825927734375, 1326.02294921875, 1301.021728515625, 1276.0250244140625, 1249.665283203125, 1223.3717041015625, 1196.60693359375, 1169.2950439453125, 1141.5545654296875, 1114.23828125, 1085.729248046875, 1057.8538818359375, 1029.1341552734375, 1001.12890625, 972.7599487304688, 944.7214965820312, 916.9534301757812, 889.0910034179688, 861.4013671875, 834.2427978515625, 807.285888671875, 780.7433471679688, 754.7882080078125, 728.7315063476562, 703.4111328125, 678.7494506835938, 654.3960571289062, 630.7374877929688, 607.8877563476562, 585.441162109375, 563.4891967773438, 542.5115966796875, 521.974609375, 502.07867431640625, 483.3244934082031, 464.6143493652344, 447.0362854003906]

In [11]:
# Mean value of the Losses throughout the Training
print(np.mean(mse_list))

1037.3733087158203

In [12]:
# Standard Deviation of the Losses throughout the Training
print(np.std(mse_list))

364.3881821915425