## Reading data from dataset

In [1]:
# For avoiding future warnings while training model
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
# Reading data from CSV
data = pd.read_csv('concrete_data.csv')
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
# Specifying columns for the predictors and target values
data_columns = data.columns
predictors = data[data_columns[data_columns != 'Strength']]
target = data['Strength']

In [4]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [5]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

## Normalizing the data

In [6]:
# Normalize data by subtracting the mean from the individual predictors and dividing by standard deviation
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

## Splitting the data

In [7]:
# Using Train Test Split from SKLEARN LIBRARY
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    predictors_norm, target, test_size=0.3, random_state=42)

# Training data = 70% and Testing Data = 30%

## Building a Neural Network

In [8]:
# Importing the Keras Library for creating model
import keras
from keras.models import Sequential
from keras.layers import Dense

## Train and Test the Network
Here, we are creating a model which has 1 Hidden Layer of 10 nodes and Activation Function is ReLU. Optimizer is adam and Loss Function is mean_squared_error. We are storing the loss values in a list as well... there are 50 epochs

In [9]:
# create model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(predictors_norm.shape[1],)))
model.add(Dense(1))

# compiling model with MSE as the Loss Function
model.compile(optimizer='adam', loss='mse')

# Train the model and store the history
history = model.fit(X_train, y_train, epochs=100)

# Storing the MSE values in the list
mse_list = history.history['loss']

C:\Users\Lakshya Saxena\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1689.8871
Epoch 2/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1612.7262
Epoch 3/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1542.6060
Epoch 4/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1541.6252
Epoch 5/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1592.5720
Epoch 6/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1501.0110
Epoch 7/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1566.0499
Epoch 8/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1574.8268
Epoch 9/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1451.1603
Epoch 10/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1525.7147
Epoch 11/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1453.8761
Epoch 12/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1557.4644
Epoch 13/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1365.9941
Epoch 14/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1455.3324
Epoch 15/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1441.7388
Epoch 16/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1351.8359
Epoch 17/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1329.2050
Epoch 18/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1268.0126
Epoch 19/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1329.0515
Epoch 20/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1241.5719
Epoch 21/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1208.0507
Epoch 22/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.6154
Epoch 23/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1174.9301
Epoch 24/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1188.5789
Epoch 25/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1106.5089
Epoch 26/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1144.9828
Epoch 27/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1056.8807
Epoch 28/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1039.5848
Epoch 29/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - loss: 1023.7507
Epoch 30/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - loss: 1014.4119
Epoch 31/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - loss: 900.5397
Epoch 32/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 881.6851
Epoch 33/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 862.5017
Epoch 34/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 845.8588
Epoch 35/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 817.3566
Epoch 36/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 818.6453
Epoch 37/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 797.4882
Epoch 38/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 739.6320
Epoch 39/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 697.6516
Epoch 40/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 709.6235
Epoch 41/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 653.8040
Epoch 42/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - loss: 627.6722
Epoch 43/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 611.5996
Epoch 44/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 619.0820
Epoch 45/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 522.9938
Epoch 46/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 510.1805
Epoch 47/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 531.7724
Epoch 48/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 460.4572
Epoch 49/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 468.6781
Epoch 50/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 433.5552
Epoch 51/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 409.5669
Epoch 52/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 413.8281
Epoch 53/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 378.3463
Epoch 54/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 375.7144
Epoch 55/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 361.1148
Epoch 56/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 359.3191
Epoch 57/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 369.9215
Epoch 58/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 335.2978
Epoch 59/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - loss: 336.9748
Epoch 60/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 294.8498
Epoch 61/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 295.9984
Epoch 62/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 278.6505
Epoch 63/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 287.6673
Epoch 64/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 266.8179
Epoch 65/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 270.2159
Epoch 66/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 281.4856
Epoch 67/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 269.7105
Epoch 68/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - loss: 254.3369
Epoch 69/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 240.0718
Epoch 70/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 254.8296
Epoch 71/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 245.6083
Epoch 72/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 246.5626
Epoch 73/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 231.3459
Epoch 74/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 243.0119
Epoch 75/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 234.1770
Epoch 76/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 229.8280
Epoch 77/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 229.2935
Epoch 78/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 221.9310
Epoch 79/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 199.1546
Epoch 80/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 208.2263
Epoch 81/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 189.3138
Epoch 82/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 203.9706
Epoch 83/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 194.6057
Epoch 84/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 205.3484
Epoch 85/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - loss: 197.3867
Epoch 86/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 207.0352
Epoch 87/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 182.8158
Epoch 88/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 186.4764
Epoch 89/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 193.1102
Epoch 90/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 205.1931
Epoch 91/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 189.5916
Epoch 92/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 191.4772
Epoch 93/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 185.0719
Epoch 94/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 174.6873
Epoch 95/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 175.0225
Epoch 96/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 181.5804
Epoch 97/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 176.7430
Epoch 98/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 180.5635
Epoch 99/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 171.6532
Epoch 100/100
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - loss: 185.1761

In [10]:
print(mse_list)

[1639.0660400390625, 1622.3348388671875, 1606.38330078125, 1590.490234375, 1575.18359375, 1559.634521484375, 1544.267333984375, 1528.621337890625, 1512.408447265625, 1495.91748046875, 1478.648193359375, 1460.6468505859375, 1441.3291015625, 1421.81201171875, 1400.7003173828125, 1378.9630126953125, 1356.2591552734375, 1332.52978515625, 1307.668212890625, 1281.6463623046875, 1254.57861328125, 1226.8330078125, 1197.8941650390625, 1168.3984375, 1137.943603515625, 1107.4422607421875, 1075.8399658203125, 1044.052001953125, 1012.4102783203125, 980.12353515625, 948.4292602539062, 916.9486694335938, 885.4164428710938, 854.13671875, 823.3263549804688, 793.2716064453125, 763.11328125, 733.7310791015625, 704.928466796875, 677.0960693359375, 649.2974243164062, 622.904052734375, 597.1276245117188, 572.3992919921875, 547.9932861328125, 525.2789306640625, 503.83892822265625, 482.7110290527344, 463.2928161621094, 444.39117431640625, 426.7463073730469, 410.29632568359375, 394.8746032714844, 380.0094909667969, 366.4743957519531, 353.6643371582031, 341.64434814453125, 330.4846496582031, 319.7818908691406, 310.1299743652344, 301.3138122558594, 292.76416015625, 285.0791931152344, 277.8553161621094, 271.1556091308594, 264.9958801269531, 259.0950622558594, 253.77499389648438, 248.73570251464844, 244.19998168945312, 239.60829162597656, 235.54930114746094, 231.74928283691406, 228.12979125976562, 224.87196350097656, 221.48577880859375, 218.40289306640625, 215.4966583251953, 212.62939453125, 209.936767578125, 207.4496612548828, 205.03785705566406, 202.69158935546875, 200.57212829589844, 198.38656616210938, 196.46510314941406, 194.4813232421875, 192.62747192382812, 190.7915802001953, 188.9604949951172, 187.2528533935547, 185.61483764648438, 183.88319396972656, 182.33953857421875, 180.72642517089844, 179.15200805664062, 177.70413208007812, 176.18511962890625, 174.70925903320312, 173.18699645996094]

In [11]:
# Mean value of the Losses throughout the Training
print(np.mean(mse_list))

665.9881280517578

In [12]:
# Standard Deviation of the Losses throughout the Training
print(np.std(mse_list))

500.0847159389205