## Reading data from dataset

In [1]:
# For avoiding future warnings while training model
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
# Reading data from CSV
data = pd.read_csv('concrete_data.csv')
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
# Specifying columns for the predictors and target values
data_columns = data.columns
predictors = data[data_columns[data_columns != 'Strength']]
target = data['Strength']

In [4]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [5]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

## Normalizing the data

In [6]:
# Normalize data by subtracting the mean from the individual predictors and dividing by standard deviation
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

## Splitting the data

In [7]:
# Using Train Test Split from SKLEARN LIBRARY
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    predictors_norm, target, test_size=0.3, random_state=42)

# Training data = 70% and Testing Data = 30%

## Building a Neural Network

In [8]:
# Importing the Keras Library for creating model
import keras
from keras.models import Sequential
from keras.layers import Dense

## Train and Test the Network
Here, we are creating a model which has 3 Hidden Layers of 10 nodes and Activation Function is ReLU. Optimizer is adam and Loss Function is mean_squared_error. We are storing the loss values in a list as well... there are 50 epochs

In [9]:
# create model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(predictors_norm.shape[1],)))
model.add(Dense(10, activation='relu', input_shape=(predictors_norm.shape[1],)))
model.add(Dense(10, activation='relu', input_shape=(predictors_norm.shape[1],)))
model.add(Dense(1))

# compiling model with MSE as the Loss Function
model.compile(optimizer='adam', loss='mse')

# Train the model and store the history
history = model.fit(X_train, y_train, epochs=50)

# Storing the MSE values in the list
mse_list = history.history['loss']

C:\Users\Lakshya Saxena\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1570.5927
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1527.2053
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1554.1158
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1378.6794
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1285.0530
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1092.7343
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 910.4719
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 666.4620
Epoch 9/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 477.3548
Epoch 10/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 342.8206
Epoch 11/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 292.4734
Epoch 12/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 263.2248
Epoch 13/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 223.7099
Epoch 14/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 208.6522
Epoch 15/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 202.4611
Epoch 16/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 193.6978
Epoch 17/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 183.3949
Epoch 18/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 184.1634
Epoch 19/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 179.8821
Epoch 20/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 173.9657
Epoch 21/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 168.3872
Epoch 22/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 173.3334
Epoch 23/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 155.5879
Epoch 24/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 155.8070
Epoch 25/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 155.1343
Epoch 26/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 144.9022
Epoch 27/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 142.8137
Epoch 28/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 153.0318
Epoch 29/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.8222
Epoch 30/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 134.0145
Epoch 31/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 146.0136
Epoch 32/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 127.0910
Epoch 33/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 133.1632
Epoch 34/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 119.4148
Epoch 35/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 123.6070
Epoch 36/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 125.8197
Epoch 37/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 127.7936
Epoch 38/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 125.3615
Epoch 39/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 123.2123
Epoch 40/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 107.0088
Epoch 41/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 108.5806
Epoch 42/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 112.6364
Epoch 43/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 106.0945
Epoch 44/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 114.6834
Epoch 45/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 109.3304
Epoch 46/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 108.9007
Epoch 47/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99.1608
Epoch 48/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.6501
Epoch 49/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92.3603
Epoch 50/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 93.3091

In [10]:
print(mse_list)

[1548.22314453125, 1506.991455078125, 1448.0640869140625, 1360.6917724609375, 1236.6162109375, 1072.3819580078125, 870.106201171875, 649.1631469726562, 460.24835205078125, 342.1264343261719, 284.7186584472656, 254.78614807128906, 234.6688690185547, 219.07203674316406, 207.767333984375, 197.90432739257812, 189.9407958984375, 183.48236083984375, 177.39865112304688, 172.1776885986328, 167.49818420410156, 163.265625, 159.4445343017578, 155.84962463378906, 152.41073608398438, 149.2947998046875, 146.3460235595703, 143.7097625732422, 141.11099243164062, 138.7112579345703, 136.28439331054688, 133.62643432617188, 131.3188018798828, 128.76478576660156, 126.7072982788086, 124.3580551147461, 121.83573913574219, 120.08972930908203, 117.9334487915039, 115.69727325439453, 113.9057388305664, 111.54331970214844, 109.7450180053711, 107.70640563964844, 105.68917083740234, 103.74319458007812, 102.5511245727539, 100.21519470214844, 98.07046508789062, 96.44612884521484]

In [11]:
# Mean value of the Losses throughout the Training
print(np.mean(mse_list))

328.8080578613281

In [12]:
# Standard Deviation of the Losses throughout the Training
print(np.std(mse_list))

408.8877106876585